### ISSUE TITLE
hello

### ISSUE THREAD

**Issue by frog** [sotatek-vuong/tst#1]
i have inquiry for you, do you have email or whatsapp or telegram or some contact method? thank you very much :)

**Comment by fabulousvuong** [comment]
Yes, I have. But What happends and who are you?

**Comment by frog** [comment]
I have some questions about your betu-casino repository as I am working on my own iGaming platform and would like to ask in private. If you can help me out, I can offer some Ethereum or any cryptocurrency for your time and help. Let me know your contacts if you are interested :)

**Comment by fabulousvuong** [comment]
my whatsapp is +84971471913
Ok, when could i reach out to you? And how
